### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TimPietrusky** [ferluht/mushroom-atlas#1]
Hey @ferluht, I was wondering under which license this projects runs? Because I would love to use some of your code (and refactor it for react-three-fiber) to generate mushrooms for a metaverse that I'm creating that only consists of fungi and extend your code to add more species. 

Thanks!

**Comment by ferluht** [comment]
Hi!
Just mention this project somewhere
And also it will be interesting to check out that mushroomverse or whatever it is, so don't hesitate to ping me when it will be ready :)

**Comment by TimPietrusky** [comment]
Thank you! 

The project I'm working on uses AGPL and will be open source on GitHub, so I will only get inspired by your code and not copy anything, but will mention this project as a reference. 

I will ping you once the first version is there 🙏
